# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: C:/hdl_projects/Z7-20/hdmi_out/src/constraints/ArtyZ7_B.xdc

# Block Designs: bd/hdmi_out/hdmi_out.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out || ORIG_REF_NAME==hdmi_out}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_dynclk_0_0/hdmi_out_axi_dynclk_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_dynclk_0_0 || ORIG_REF_NAME==hdmi_out_axi_dynclk_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_mem_intercon_0/hdmi_out_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_mem_intercon_0 || ORIG_REF_NAME==hdmi_out_axi_mem_intercon_0}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_out_axi_vdma_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdmi_out_axis_subset_converter_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axis_subset_converter_0_0 || ORIG_REF_NAME==hdmi_out_axis_subset_converter_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_1_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_1_0}]

# IP: bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_ps7_0_axi_periph_0/hdmi_out_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_ps7_0_axi_periph_0 || ORIG_REF_NAME==hdmi_out_ps7_0_axi_periph_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xbar_0 || ORIG_REF_NAME==hdmi_out_xbar_0}]

# IP: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/hdmi_out_rgb2dvi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_out_v_axi4s_vid_out_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xlconcat_0_0/hdmi_out_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconcat_0_0 || ORIG_REF_NAME==hdmi_out_xlconcat_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xlconstant_1_0/hdmi_out_xlconstant_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xlconstant_1_0 || ORIG_REF_NAME==hdmi_out_xlconstant_1_0}]

# IP: bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/hdmi_out_dvi2rgb_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_out_dvi2rgb_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/hdmi_out_v_vid_in_axi4s_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_out_v_vid_in_axi4s_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_v_tc_1_0/hdmi_out_v_tc_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_1_0 || ORIG_REF_NAME==hdmi_out_v_tc_1_0}]

# IP: bd/hdmi_out/ip/hdmi_out_xbar_1/hdmi_out_xbar_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_xbar_1 || ORIG_REF_NAME==hdmi_out_xbar_1}]

# IP: bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_out_axi_quad_spi_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_ila_0_0/hdmi_out_ila_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_ila_0_0 || ORIG_REF_NAME==hdmi_out_ila_0_0}]

# IP: bd/hdmi_out/ip/hdmi_out_s00_regslice_0/hdmi_out_s00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_s00_regslice_0 || ORIG_REF_NAME==hdmi_out_s00_regslice_0}]

# IP: bd/hdmi_out/ip/hdmi_out_s00_data_fifo_0/hdmi_out_s00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_s00_data_fifo_0 || ORIG_REF_NAME==hdmi_out_s00_data_fifo_0}]

# IP: bd/hdmi_out/ip/hdmi_out_s01_regslice_0/hdmi_out_s01_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_s01_regslice_0 || ORIG_REF_NAME==hdmi_out_s01_regslice_0}]

# IP: bd/hdmi_out/ip/hdmi_out_m00_data_fifo_0/hdmi_out_m00_data_fifo_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_m00_data_fifo_0 || ORIG_REF_NAME==hdmi_out_m00_data_fifo_0}]

# IP: bd/hdmi_out/ip/hdmi_out_m00_regslice_0/hdmi_out_m00_regslice_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_m00_regslice_0 || ORIG_REF_NAME==hdmi_out_m00_regslice_0}]

# IP: bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_auto_pc_0 || ORIG_REF_NAME==hdmi_out_auto_pc_0}]

# IP: bd/hdmi_out/ip/hdmi_out_auto_us_df_0/hdmi_out_auto_us_df_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_auto_us_df_0 || ORIG_REF_NAME==hdmi_out_auto_us_df_0}]

# IP: bd/hdmi_out/ip/hdmi_out_auto_pc_1/hdmi_out_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==hdmi_out_auto_pc_1 || ORIG_REF_NAME==hdmi_out_auto_pc_1}]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_gpio_hdmi_0 || ORIG_REF_NAME==hdmi_out_axi_gpio_hdmi_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_out_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_vdma_0_0 || ORIG_REF_NAME==hdmi_out_axi_vdma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdmi_out_axis_subset_converter_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_0_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_1_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_proc_sys_reset_1_0 || ORIG_REF_NAME==hdmi_out_proc_sys_reset_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_processing_system7_0_0 || ORIG_REF_NAME==hdmi_out_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_rgb2dvi_0_0 || ORIG_REF_NAME==hdmi_out_rgb2dvi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_axi4s_vid_out_0_0 || ORIG_REF_NAME==hdmi_out_v_axi4s_vid_out_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_0_0 || ORIG_REF_NAME==hdmi_out_v_tc_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/src/dvi2rgb.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_dvi2rgb_0_0 || ORIG_REF_NAME==hdmi_out_dvi2rgb_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/hdmi_out_v_vid_in_axi4s_0_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_vid_in_axi4s_0_0 || ORIG_REF_NAME==hdmi_out_v_vid_in_axi4s_0_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/hdmi_out_v_vid_in_axi4s_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_1_0/hdmi_out_v_tc_1_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_v_tc_1_0 || ORIG_REF_NAME==hdmi_out_v_tc_1_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_v_tc_1_0/hdmi_out_v_tc_1_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_xbar_1/hdmi_out_xbar_1_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_out_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_out_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_axi_quad_spi_0_0 || ORIG_REF_NAME==hdmi_out_axi_quad_spi_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_ila_0_0/ila_v6_2/constraints/ila.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_ila_0_0 || ORIG_REF_NAME==hdmi_out_ila_0_0}] {/U0 }]/U0 ]]

# XDC: bd/hdmi_out/ip/hdmi_out_ila_0_0/hdmi_out_ila_0_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_s00_regslice_0/hdmi_out_s00_regslice_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_s00_data_fifo_0/hdmi_out_s00_data_fifo_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_s01_regslice_0/hdmi_out_s01_regslice_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_m00_data_fifo_0/hdmi_out_m00_data_fifo_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_m00_regslice_0/hdmi_out_m00_regslice_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_auto_us_df_0/hdmi_out_auto_us_df_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==hdmi_out_auto_us_df_0 || ORIG_REF_NAME==hdmi_out_auto_us_df_0}] {/inst }]/inst ]]

# XDC: bd/hdmi_out/ip/hdmi_out_auto_us_df_0/hdmi_out_auto_us_df_0_ooc.xdc

# XDC: bd/hdmi_out/ip/hdmi_out_auto_pc_1/hdmi_out_auto_pc_1_ooc.xdc

# XDC: bd/hdmi_out/hdmi_out_ooc.xdc
