# 
# Synthesis run script generated by Vivado
# 

set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.cache/wt [current_project]
set_property parent.project_path C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:arty-z7-20:part0:1.0 [current_project]
set_property ip_repo_paths c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.ipdefs/digilent_0 [current_project]
set_property ip_output_repo c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/hdl/hdmi_out_wrapper.vhd
add_files C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/hdmi_out.bd
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/hdmi_out_axi_gpio_hdmi_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/hdmi_out_axi_vdma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdmi_out_axis_subset_converter_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/hdmi_out_proc_sys_reset_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/hdmi_out_proc_sys_reset_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/hdmi_out_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_0/hdmi_out_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/src/rgb2dvi_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/hdmi_out_v_axi4s_vid_out_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/hdmi_out_v_tc_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/src/dvi2rgb.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/src/dvi2rgb_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/hdmi_out_v_vid_in_axi4s_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/hdmi_out_v_vid_in_axi4s_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_1_0/hdmi_out_v_tc_1_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_1_0/hdmi_out_v_tc_1_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_1/hdmi_out_xbar_1_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_board.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/hdmi_out_axi_quad_spi_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_ila_0_0/ila_v6_2/constraints/ila.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_ila_0_0/hdmi_out_ila_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s00_regslice_0/hdmi_out_s00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s00_data_fifo_0/hdmi_out_s00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s01_regslice_0/hdmi_out_s01_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_m00_data_fifo_0/hdmi_out_m00_data_fifo_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_m00_regslice_0/hdmi_out_m00_regslice_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_0/hdmi_out_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_us_df_0/hdmi_out_auto_us_df_0_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_us_df_0/hdmi_out_auto_us_df_0_ooc.xdc]
set_property used_in_implementation false [get_files -all c:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_1/hdmi_out_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/hdmi_out_ooc.xdc]
set_property is_locked true [get_files C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/sources_1/bd/hdmi_out/hdmi_out.bd]

foreach dcp [get_files -quiet -all *.dcp] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/constrs_1/imports/constraints/ArtyZ7_B.xdc
set_property used_in_implementation false [get_files C:/Users/aptay/Documents/GitHub/FLIR_LEPTON2/hdmi_out/hdmi_out.srcs/constrs_1/imports/constraints/ArtyZ7_B.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top hdmi_out_wrapper -part xc7z020clg400-1 -flatten_hierarchy none -directive RuntimeOptimized -fsm_extraction off


write_checkpoint -force -noxdef hdmi_out_wrapper.dcp

catch { report_utilization -file hdmi_out_wrapper_utilization_synth.rpt -pb hdmi_out_wrapper_utilization_synth.pb }
