#!/bin/bash -f
# Vivado (TM) v2016.4 (64-bit)
#
# Filename    : hdmi_out.sh
# Simulator   : Synopsys Verilog Compiler Simulator
# Description : Simulation script for compiling, elaborating and verifying the project source files.
#               The script will automatically create the design libraries sub-directories in the run
#               directory, add the library logical mappings in the simulator setup file, create default
#               'do/prj' file, execute compilation, elaboration and simulation steps.
#
# Generated by Vivado on Thu Jun 22 20:47:12 +0100 2017
# IP Build 1755317 on Mon Jan 23 20:30:07 MST 2017 
#
# usage: hdmi_out.sh [-help]
# usage: hdmi_out.sh [-lib_map_path]
# usage: hdmi_out.sh [-noclean_files]
# usage: hdmi_out.sh [-reset_run]
#
# Prerequisite:- To compile and run simulation, you must compile the Xilinx simulation libraries using the
# 'compile_simlib' TCL command. For more information about this command, run 'compile_simlib -help' in the
# Vivado Tcl Shell. Once the libraries have been compiled successfully, specify the -lib_map_path switch
# that points to these libraries and rerun export_simulation. For more information about this switch please
# type 'export_simulation -help' in the Tcl shell.
#
# You can also point to the simulation libraries by either replacing the <SPECIFY_COMPILED_LIB_PATH> in this
# script with the compiled library directory path or specify this path with the '-lib_map_path' switch when
# executing this script. Please type 'hdmi_out.sh -help' for more information.
#
# Additional references - 'Xilinx Vivado Design Suite User Guide:Logic simulation (UG900)'
#
# ********************************************************************************************************

# Directory path for design sources and include directories (if any) wrt this path
ref_dir="."

# Override directory with 'export_sim_ref_dir' env path value if set in the shell
if [[ (! -z "$export_sim_ref_dir") && ($export_sim_ref_dir != "") ]]; then
  ref_dir="$export_sim_ref_dir"
fi

# Command line options
vlogan_opts="-full64"
vhdlan_opts="-full64"
vcs_elab_opts="-load "C:/Xilinx/Vivado/2016.4/lib/win64.o/libxil_vcs.dll:xilinx_register_systf" -full64 -debug_pp -t ps -licqueue -l elaborate.log"
vcs_sim_opts="-ucli -licqueue -l simulate.log"

# Design libraries
design_libs=(xil_defaultlib xpm axi_lite_ipif_v3_0_4 lib_cdc_v1_0_2 interrupt_control_v3_1_4 axi_gpio_v2_0_13 lib_pkg_v1_0_2 fifo_generator_v13_1_3 lib_fifo_v1_0_7 blk_mem_gen_v8_3_5 lib_bmg_v1_0_7 lib_srl_fifo_v1_0_2 axi_datamover_v5_1_13 axi_vdma_v6_2_10 axis_infrastructure_v1_1_0 axis_register_slice_v1_1_11 axis_subset_converter_v1_1_11 proc_sys_reset_v5_0_10 processing_system7_bfm_v2_0_5 generic_baseblocks_v2_1_0 axi_infrastructure_v1_1_0 axi_register_slice_v2_1_11 axi_data_fifo_v2_1_10 axi_crossbar_v2_1_12 v_tc_v6_1_10 v_vid_in_axi4s_v4_0_5 v_axi4s_vid_out_v4_0_5 dist_mem_gen_v8_0_11 axi_quad_spi_v3_2_10 axi_protocol_converter_v2_1_11 axi_clock_converter_v2_1_10 axi_dwidth_converter_v2_1_11)

# Simulation root library directory
sim_lib_dir="vcs"

# Script info
echo -e "hdmi_out.sh - Script generated by export_simulation (Vivado v2016.4 (64-bit)-id)\n"

# Main steps
run()
{
  check_args $# $1
  setup $1 $2
  compile
  elaborate
  simulate
}

# RUN_STEP: <compile>
compile()
{
  # Compile design files
  vlogan -work xil_defaultlib $vlogan_opts -sverilog +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "C:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv" \
    "C:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xpm $vhdlan_opts \
    "C:/Xilinx/Vivado/2016.4/data/ip/xpm/xpm_VCOMP.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/9097/src/mmcme2_drp.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/9097/src/axi_dynclk_S00_AXI.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/9097/src/axi_dynclk.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_dynclk_0_0/sim/hdmi_out_axi_dynclk_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_lite_ipif_v3_0_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0ba0/hdl/axi_lite_ipif_v3_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_cdc_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/52cb/hdl/lib_cdc_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work interrupt_control_v3_1_4 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/e956/hdl/interrupt_control_v3_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_gpio_v2_0_13 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/4f16/hdl/axi_gpio_v2_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_gpio_hdmi_0/sim/hdmi_out_axi_gpio_hdmi_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_pkg_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/832a/hdl/lib_pkg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/564d/simulation/fifo_generator_vlog_beh.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work fifo_generator_v13_1_3 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/564d/hdl/fifo_generator_v13_1_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work fifo_generator_v13_1_3 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/564d/hdl/fifo_generator_v13_1_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_fifo_v1_0_7 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/5ab6/hdl/lib_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work blk_mem_gen_v8_3_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/6273/simulation/blk_mem_gen_v8_3.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work lib_bmg_v1_0_7 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/38e8/hdl/lib_bmg_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work lib_srl_fifo_v1_0_2 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/6039/hdl/lib_srl_fifo_v1_0_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work axi_datamover_v5_1_13 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/bf41/hdl/axi_datamover_v5_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axi_vdma_v6_2_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl/axi_vdma_v6_2_rfs.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_vdma_v6_2_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl/axi_vdma_v6_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_vdma_0_0/sim/hdmi_out_axi_vdma_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work axis_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl/axis_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_register_slice_v1_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/09aa/hdl/axis_register_slice_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tdata_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tuser_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tstrb_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tkeep_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tid_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tdest_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/tlast_hdmi_out_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axis_subset_converter_v1_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/8a5f/hdl/axis_subset_converter_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/hdl/top_hdmi_out_axis_subset_converter_0_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axis_subset_converter_0_0/sim/hdmi_out_axis_subset_converter_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work proc_sys_reset_v5_0_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/04b4/hdl/proc_sys_reset_v5_0_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_0_0/sim/hdmi_out_proc_sys_reset_0_0.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_proc_sys_reset_1_0/sim/hdmi_out_proc_sys_reset_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work processing_system7_bfm_v2_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl/processing_system7_bfm_v2_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_processing_system7_0_0/sim/hdmi_out_processing_system7_0_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work generic_baseblocks_v2_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7ee0/hdl/generic_baseblocks_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_infrastructure_v1_1_0 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl/axi_infrastructure_v1_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_register_slice_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0b6b/hdl/axi_register_slice_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_data_fifo_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/39ba/hdl/axi_data_fifo_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_crossbar_v2_1_12 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/896d/hdl/axi_crossbar_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_0/sim/hdmi_out_xbar_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/ClockGen.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/SyncAsync.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/SyncAsyncReset.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/DVI_Constants.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/OutputSERDES.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/TMDS_Encoder.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/dc1a/src/rgb2dvi.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_rgb2dvi_0_0/sim/hdmi_out_rgb2dvi_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work v_tc_v6_1_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/d9f8/hdl/v_tc_v6_1_vh_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work v_vid_in_axi4s_v4_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/3c71/hdl/v_vid_in_axi4s_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work v_axi4s_vid_out_v4_0_5 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/1923/hdl/v_axi4s_vid_out_v4_0_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_axi4s_vid_out_0_0/sim/hdmi_out_v_axi4s_vid_out_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_0_0/sim/hdmi_out_v_tc_0_0.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/2e37/xlconcat.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xlconcat_0_0/sim/hdmi_out_xlconcat_0_0.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/e147/xlconstant.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xlconstant_1_0/sim/hdmi_out_xlconstant_1_0.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/SyncBase.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/EEPROM_8b.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/TWI_SlaveCtl.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/GlitchFilter.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/PhaseAlign.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/InputSERDES.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/ChannelBond.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/ResyncToBUFG.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/TMDS_Decoder.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/TMDS_Clocking.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/269e/src/dvi2rgb.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_dvi2rgb_0_0/sim/hdmi_out_dvi2rgb_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_vid_in_axi4s_0_0/sim/hdmi_out_v_vid_in_axi4s_0_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_v_tc_1_0/sim/hdmi_out_v_tc_1_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_xbar_1/sim/hdmi_out_xbar_1.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work dist_mem_gen_v8_0_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ec0d/simulation/dist_mem_gen_v8_0.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work axi_quad_spi_v3_2_10 $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/e7ca/hdl/axi_quad_spi_v3_2_rfs.vhd" \
  2>&1 | tee -a vhdlan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_axi_quad_spi_0_0/sim/hdmi_out_axi_quad_spi_0_0.vhd" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_ila_0_0/sim/hdmi_out_ila_0_0.vhd" \
  2>&1 | tee -a vhdlan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s00_regslice_0/sim/hdmi_out_s00_regslice_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s00_data_fifo_0/sim/hdmi_out_s00_data_fifo_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_s01_regslice_0/sim/hdmi_out_s01_regslice_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_m00_data_fifo_0/sim/hdmi_out_m00_data_fifo_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_m00_regslice_0/sim/hdmi_out_m00_regslice_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_protocol_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/df1b/hdl/axi_protocol_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_0/sim/hdmi_out_auto_pc_0.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_clock_converter_v2_1_10 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/8479/hdl/axi_clock_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work axi_dwidth_converter_v2_1_11 $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/a4c8/hdl/axi_dwidth_converter_v2_1_vl_rfs.v" \
  2>&1 | tee -a vlogan.log

  vlogan -work xil_defaultlib $vlogan_opts +v2k +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/ed72/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/fe67/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7dd0/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/7e3a/hdl" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/0cab/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/f9cc/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/469d/hdl/verilog" +incdir+"$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ipshared/48e6/hdl/verilog" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_us_df_0/sim/hdmi_out_auto_us_df_0.v" \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/ip/hdmi_out_auto_pc_1/sim/hdmi_out_auto_pc_1.v" \
  2>&1 | tee -a vlogan.log

  vhdlan -work xil_defaultlib $vhdlan_opts \
    "$ref_dir/../../../../hdmi_out.srcs/sources_1/bd/hdmi_out/hdl/hdmi_out.vhd" \
  2>&1 | tee -a vhdlan.log


  vlogan -work xil_defaultlib $vlogan_opts +v2k \
    glbl.v \
  2>&1 | tee -a vlogan.log

}

# RUN_STEP: <elaborate>
elaborate()
{
  vcs $vcs_elab_opts xil_defaultlib.hdmi_out xil_defaultlib.glbl -o hdmi_out_simv
}

# RUN_STEP: <simulate>
simulate()
{
  ./hdmi_out_simv $vcs_sim_opts -do simulate.do
}

# STEP: setup
setup()
{
  case $1 in
    "-lib_map_path" )
      if [[ ($2 == "") ]]; then
        echo -e "ERROR: Simulation library directory path not specified (type \"./hdmi_out.sh -help\" for more information)\n"
        exit 1
      fi
      create_lib_mappings $2
    ;;
    "-reset_run" )
      reset_run
      echo -e "INFO: Simulation run files deleted.\n"
      exit 0
    ;;
    "-noclean_files" )
      # do not remove previous data
    ;;
    * )
      create_lib_mappings $2
  esac

  create_lib_dir

  # Add any setup/initialization commands here:-

  # <user specific commands>

}

# Define design library mappings
create_lib_mappings()
{
  file="synopsys_sim.setup"
  if [[ -e $file ]]; then
    if [[ ($1 == "") ]]; then
      return
    else
      rm -rf $file
    fi
  fi

  touch $file

  lib_map_path=""
  if [[ ($1 != "") ]]; then
    lib_map_path="$1"
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    mapping="$lib:$sim_lib_dir/$lib"
    echo $mapping >> $file
  done

  if [[ ($lib_map_path != "") ]]; then
    incl_ref="OTHERS=$lib_map_path/synopsys_sim.setup"
    echo $incl_ref >> $file
  fi
}

# Create design library directory paths
create_lib_dir()
{
  if [[ -e $sim_lib_dir ]]; then
    rm -rf $sim_lib_dir
  fi

  for (( i=0; i<${#design_libs[*]}; i++ )); do
    lib="${design_libs[i]}"
    lib_dir="$sim_lib_dir/$lib"
    if [[ ! -e $lib_dir ]]; then
      mkdir -p $lib_dir
    fi
  done
}

# Delete generated data from the previous run
reset_run()
{
  files_to_remove=(ucli.key hdmi_out_simv vlogan.log vhdlan.log compile.log elaborate.log simulate.log .vlogansetup.env .vlogansetup.args .vcs_lib_lock scirocco_command.log 64 AN.DB csrc hdmi_out_simv.daidir)
  for (( i=0; i<${#files_to_remove[*]}; i++ )); do
    file="${files_to_remove[i]}"
    if [[ -e $file ]]; then
      rm -rf $file
    fi
  done

  create_lib_dir
}

# Check command line arguments
check_args()
{
  if [[ ($1 == 1 ) && ($2 != "-lib_map_path" && $2 != "-noclean_files" && $2 != "-reset_run" && $2 != "-help" && $2 != "-h") ]]; then
    echo -e "ERROR: Unknown option specified '$2' (type \"./hdmi_out.sh -help\" for more information)\n"
    exit 1
  fi

  if [[ ($2 == "-help" || $2 == "-h") ]]; then
    usage
  fi
}

# Script usage
usage()
{
  msg="Usage: hdmi_out.sh [-help]\n\
Usage: hdmi_out.sh [-lib_map_path]\n\
Usage: hdmi_out.sh [-reset_run]\n\
Usage: hdmi_out.sh [-noclean_files]\n\n\
[-help] -- Print help information for this script\n\n\
[-lib_map_path <path>] -- Compiled simulation library directory path. The simulation library is compiled\n\
using the compile_simlib tcl command. Please see 'compile_simlib -help' for more information.\n\n\
[-reset_run] -- Recreate simulator setup files and library mappings for a clean run. The generated files\n\
from the previous run will be removed. If you don't want to remove the simulator generated files, use the\n\
-noclean_files switch.\n\n\
[-noclean_files] -- Reset previous run, but do not remove simulator generated files from the previous run.\n\n"
  echo -e $msg
  exit 1
}

# Launch script
run $1 $2
